/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RiskLevel = IDL.Variant({
  'normal' : IDL.Null,
  'high' : IDL.Null,
  'moderate' : IDL.Null,
});
export const VisitHistoryRecord = IDL.Record({
  'weight' : IDL.Float64,
  'visitDate' : IDL.Int,
  'bloodPressure' : IDL.Nat,
  'hemoglobin' : IDL.Float64,
  'notes' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BMIRecord = IDL.Record({
  'age' : IDL.Nat,
  'bmi' : IDL.Float64,
  'heightCm' : IDL.Float64,
  'name' : IDL.Text,
  'weightKg' : IDL.Float64,
  'gender' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const VisitHistoryRecordView = IDL.Record({
  'weight' : IDL.Float64,
  'visitDate' : IDL.Int,
  'bloodPressure' : IDL.Nat,
  'hemoglobin' : IDL.Float64,
  'notes' : IDL.Text,
});
export const PregnancyRecordView = IDL.Record({
  'age' : IDL.Nat,
  'weight' : IDL.Float64,
  'trimester' : IDL.Nat,
  'eddDate' : IDL.Int,
  'visitHistory' : IDL.Vec(VisitHistoryRecordView),
  'name' : IDL.Text,
  'bloodPressure' : IDL.Nat,
  'husbandName' : IDL.Text,
  'address' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'lmpDate' : IDL.Int,
  'gestationalAge' : IDL.Nat,
  'riskLevel' : RiskLevel,
  'hemoglobinLevel' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBMIRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Int,
      ],
      [],
      [],
    ),
  'addPregnancyRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Int,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Nat,
        RiskLevel,
        VisitHistoryRecord,
      ],
      [],
      [],
    ),
  'addVisit' : IDL.Func([IDL.Text, VisitHistoryRecord], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllBMIRecords' : IDL.Func([], [IDL.Vec(BMIRecord)], ['query']),
  'getAllPregnancyRecords' : IDL.Func(
      [],
      [IDL.Vec(PregnancyRecordView)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getIndex' : IDL.Func([IDL.Nat], [IDL.Int], []),
  'getLatestBMIRecords' : IDL.Func([IDL.Nat], [IDL.Vec(BMIRecord)], ['query']),
  'getNowTimestamp' : IDL.Func([], [IDL.Int], []),
  'getPregnanciesByRiskLevel' : IDL.Func(
      [RiskLevel],
      [IDL.Vec(PregnancyRecordView)],
      ['query'],
    ),
  'getPregnancyByPhoneNumber' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PregnancyRecordView)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RiskLevel = IDL.Variant({
    'normal' : IDL.Null,
    'high' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const VisitHistoryRecord = IDL.Record({
    'weight' : IDL.Float64,
    'visitDate' : IDL.Int,
    'bloodPressure' : IDL.Nat,
    'hemoglobin' : IDL.Float64,
    'notes' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BMIRecord = IDL.Record({
    'age' : IDL.Nat,
    'bmi' : IDL.Float64,
    'heightCm' : IDL.Float64,
    'name' : IDL.Text,
    'weightKg' : IDL.Float64,
    'gender' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const VisitHistoryRecordView = IDL.Record({
    'weight' : IDL.Float64,
    'visitDate' : IDL.Int,
    'bloodPressure' : IDL.Nat,
    'hemoglobin' : IDL.Float64,
    'notes' : IDL.Text,
  });
  const PregnancyRecordView = IDL.Record({
    'age' : IDL.Nat,
    'weight' : IDL.Float64,
    'trimester' : IDL.Nat,
    'eddDate' : IDL.Int,
    'visitHistory' : IDL.Vec(VisitHistoryRecordView),
    'name' : IDL.Text,
    'bloodPressure' : IDL.Nat,
    'husbandName' : IDL.Text,
    'address' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'lmpDate' : IDL.Int,
    'gestationalAge' : IDL.Nat,
    'riskLevel' : RiskLevel,
    'hemoglobinLevel' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBMIRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Int,
        ],
        [],
        [],
      ),
    'addPregnancyRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Int,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Nat,
          RiskLevel,
          VisitHistoryRecord,
        ],
        [],
        [],
      ),
    'addVisit' : IDL.Func([IDL.Text, VisitHistoryRecord], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllBMIRecords' : IDL.Func([], [IDL.Vec(BMIRecord)], ['query']),
    'getAllPregnancyRecords' : IDL.Func(
        [],
        [IDL.Vec(PregnancyRecordView)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getIndex' : IDL.Func([IDL.Nat], [IDL.Int], []),
    'getLatestBMIRecords' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(BMIRecord)],
        ['query'],
      ),
    'getNowTimestamp' : IDL.Func([], [IDL.Int], []),
    'getPregnanciesByRiskLevel' : IDL.Func(
        [RiskLevel],
        [IDL.Vec(PregnancyRecordView)],
        ['query'],
      ),
    'getPregnancyByPhoneNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PregnancyRecordView)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };