/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PregnancyRecordView {
  'age' : bigint,
  'weight' : number,
  'trimester' : bigint,
  'eddDate' : bigint,
  'visitHistory' : Array<VisitHistoryRecordView>,
  'name' : string,
  'bloodPressure' : bigint,
  'husbandName' : string,
  'address' : string,
  'phoneNumber' : string,
  'lmpDate' : bigint,
  'gestationalAge' : bigint,
  'riskLevel' : RiskLevel,
  'hemoglobinLevel' : number,
}
export type RiskLevel = { 'normal' : null } |
  { 'high' : null } |
  { 'moderate' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VisitHistoryRecord {
  'weight' : number,
  'visitDate' : bigint,
  'bloodPressure' : bigint,
  'hemoglobin' : number,
  'notes' : string,
}
export interface VisitHistoryRecordView {
  'weight' : number,
  'visitDate' : bigint,
  'bloodPressure' : bigint,
  'hemoglobin' : number,
  'notes' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPregnancyRecord' : ActorMethod<
    [
      string,
      bigint,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      number,
      number,
      bigint,
      bigint,
      RiskLevel,
      VisitHistoryRecord,
    ],
    undefined
  >,
  'addVisit' : ActorMethod<[string, VisitHistoryRecord], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllPregnancyRecords' : ActorMethod<[], Array<PregnancyRecordView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getIndex' : ActorMethod<[bigint], bigint>,
  'getNowTimestamp' : ActorMethod<[], bigint>,
  'getPregnanciesByRiskLevel' : ActorMethod<
    [RiskLevel],
    Array<PregnancyRecordView>
  >,
  'getPregnancyByPhoneNumber' : ActorMethod<
    [string],
    [] | [PregnancyRecordView]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];