/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VisitHistoryRecordView {
    weight: number;
    visitDate: bigint;
    bloodPressure: bigint;
    hemoglobin: number;
    notes: string;
}
export interface PregnancyRecordView {
    age: bigint;
    weight: number;
    trimester: bigint;
    eddDate: bigint;
    visitHistory: Array<VisitHistoryRecordView>;
    name: string;
    bloodPressure: bigint;
    husbandName: string;
    address: string;
    phoneNumber: string;
    lmpDate: bigint;
    gestationalAge: bigint;
    riskLevel: RiskLevel;
    hemoglobinLevel: number;
}
export interface VisitHistoryRecord {
    weight: number;
    visitDate: bigint;
    bloodPressure: bigint;
    hemoglobin: number;
    notes: string;
}
export interface BMIRecord {
    age: bigint;
    bmi: number;
    heightCm: number;
    name: string;
    weightKg: number;
    gender: string;
    timestamp: bigint;
}
export interface UserProfile {
    name: string;
}
export enum RiskLevel {
    normal = "normal",
    high = "high",
    moderate = "moderate"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBMIRecord(name: string, age: bigint, gender: string, heightCm: number, weightKg: number, bmi: number, timestamp: bigint): Promise<void>;
    addPregnancyRecord(name: string, age: bigint, husbandName: string, address: string, phoneNumber: string, lmpDate: bigint, eddDate: bigint, gestationalAge: bigint, weight: number, hemoglobinLevel: number, bloodPressure: bigint, trimester: bigint, riskLevel: RiskLevel, initialVisit: VisitHistoryRecord): Promise<void>;
    addVisit(phoneNumber: string, newVisit: VisitHistoryRecord): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllBMIRecords(): Promise<Array<BMIRecord>>;
    getAllPregnancyRecords(): Promise<Array<PregnancyRecordView>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getIndex(numberOfEntries: bigint): Promise<bigint>;
    getLatestBMIRecords(count: bigint): Promise<Array<BMIRecord>>;
    getNowTimestamp(): Promise<bigint>;
    getPregnanciesByRiskLevel(riskLevel: RiskLevel): Promise<Array<PregnancyRecordView>>;
    getPregnancyByPhoneNumber(phoneNumber: string): Promise<PregnancyRecordView | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { PregnancyRecordView as _PregnancyRecordView, RiskLevel as _RiskLevel, UserProfile as _UserProfile, UserRole as _UserRole, VisitHistoryRecordView as _VisitHistoryRecordView } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBMIRecord(arg0: string, arg1: bigint, arg2: string, arg3: number, arg4: number, arg5: number, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBMIRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBMIRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addPregnancyRecord(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: bigint, arg7: bigint, arg8: number, arg9: number, arg10: bigint, arg11: bigint, arg12: RiskLevel, arg13: VisitHistoryRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPregnancyRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, to_candid_RiskLevel_n1(this._uploadFile, this._downloadFile, arg12), arg13);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPregnancyRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, to_candid_RiskLevel_n1(this._uploadFile, this._downloadFile, arg12), arg13);
            return result;
        }
    }
    async addVisit(arg0: string, arg1: VisitHistoryRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVisit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVisit(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllBMIRecords(): Promise<Array<BMIRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBMIRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBMIRecords();
            return result;
        }
    }
    async getAllPregnancyRecords(): Promise<Array<PregnancyRecordView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPregnancyRecords();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPregnancyRecords();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIndex(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getIndex(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIndex(arg0);
            return result;
        }
    }
    async getLatestBMIRecords(arg0: bigint): Promise<Array<BMIRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestBMIRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestBMIRecords(arg0);
            return result;
        }
    }
    async getNowTimestamp(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNowTimestamp();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNowTimestamp();
            return result;
        }
    }
    async getPregnanciesByRiskLevel(arg0: RiskLevel): Promise<Array<PregnancyRecordView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPregnanciesByRiskLevel(to_candid_RiskLevel_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPregnanciesByRiskLevel(to_candid_RiskLevel_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPregnancyByPhoneNumber(arg0: string): Promise<PregnancyRecordView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPregnancyByPhoneNumber(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPregnancyByPhoneNumber(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_PregnancyRecordView_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PregnancyRecordView): PregnancyRecordView {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PregnancyRecordView]): PregnancyRecordView | null {
    return value.length === 0 ? null : from_candid_PregnancyRecordView_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    weight: number;
    trimester: bigint;
    eddDate: bigint;
    visitHistory: Array<_VisitHistoryRecordView>;
    name: string;
    bloodPressure: bigint;
    husbandName: string;
    address: string;
    phoneNumber: string;
    lmpDate: bigint;
    gestationalAge: bigint;
    riskLevel: _RiskLevel;
    hemoglobinLevel: number;
}): {
    age: bigint;
    weight: number;
    trimester: bigint;
    eddDate: bigint;
    visitHistory: Array<VisitHistoryRecordView>;
    name: string;
    bloodPressure: bigint;
    husbandName: string;
    address: string;
    phoneNumber: string;
    lmpDate: bigint;
    gestationalAge: bigint;
    riskLevel: RiskLevel;
    hemoglobinLevel: number;
} {
    return {
        age: value.age,
        weight: value.weight,
        trimester: value.trimester,
        eddDate: value.eddDate,
        visitHistory: value.visitHistory,
        name: value.name,
        bloodPressure: value.bloodPressure,
        husbandName: value.husbandName,
        address: value.address,
        phoneNumber: value.phoneNumber,
        lmpDate: value.lmpDate,
        gestationalAge: value.gestationalAge,
        riskLevel: from_candid_RiskLevel_n8(_uploadFile, _downloadFile, value.riskLevel),
        hemoglobinLevel: value.hemoglobinLevel
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    normal: null;
} | {
    high: null;
} | {
    moderate: null;
}): RiskLevel {
    return "normal" in value ? RiskLevel.normal : "high" in value ? RiskLevel.high : "moderate" in value ? RiskLevel.moderate : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PregnancyRecordView>): Array<PregnancyRecordView> {
    return value.map((x)=>from_candid_PregnancyRecordView_n6(_uploadFile, _downloadFile, x));
}
function to_candid_RiskLevel_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): _RiskLevel {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): {
    normal: null;
} | {
    high: null;
} | {
    moderate: null;
} {
    return value == RiskLevel.normal ? {
        normal: null
    } : value == RiskLevel.high ? {
        high: null
    } : value == RiskLevel.moderate ? {
        moderate: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
